In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../../data/original_data/human-development-index/human-development-index.csv")

In [3]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 6570 entries, 0 to 6569
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Entity                          6570 non-null   str
 1   Code                            5940 non-null   str
 2   Year                            6570 non-null   int64
 3   Human Development Index         6570 non-null   float64
 4   World region according to OWID  5906 non-null   str
dtypes: float64(1), int64(1), str(3)
memory usage: 256.8 KB
None

In [4]:
len(df['Entity'].unique())

214

In [5]:
import pycountry

In [6]:
iso3_name_set = {country.alpha_3 for country in pycountry.countries}

In [7]:
df_countries=df[df['Code'].isin(iso3_name_set)]

In [8]:
df_filtered = df_countries[
    (~(df['Human Development Index'].isna()))  
    & (df['Year'] == 2023)  
]

C:\Users\USER\AppData\Local\Temp\ipykernel_14572\768795495.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_filtered = df_countries[

## WE HAVE FILTERED DISTINCT COUNTRY VALUES FOR 2018

In [9]:
df_filtered

,Entity,Code,Year,Human Development Index,World region according to OWID
33,Afghanistan,AFG,2023,0.496,Asia
91,Albania,ALB,2023,0.810,Europe
125,Algeria,DZA,2023,0.763,Africa
149,Andorra,AND,2023,0.913,Europe
174,Angola,AGO,2023,0.616,Africa
...,...,...,...,...,...
6365,Venezuela,VEN,2023,0.709,South America
6433,Vietnam,VNM,2023,0.766,Asia
6501,Yemen,YEM,2023,0.470,Asia
6535,Zambia,ZMB,2023,0.595,Africa
6569,Zimbabwe,ZWE,2023,0.598,Africa

In [ ]:
average_hdi_per_entity =( df_filtered.groupby(
    'World region according to OWID',
    as_index=False)['Human Development Index']
    .mean()
    .rename(columns={'Human Development Index':'Average HDI'})
)
average_hdi_per_entity

  World region according to OWID  Average HDI
0                         Africa     0.579611
1                           Asia     0.756630
2                         Europe     0.899093
3                  North America     0.773435
4                        Oceania     0.718214
5                  South America     0.787167

In [12]:
max_hdi_per_region = df_filtered.groupby('World region according to OWID')['Human Development Index'].transform('max')

df_top = df_filtered[df_filtered['Human Development Index'] == max_hdi_per_region]

df_top

,Entity,Code,Year,Human Development Index,World region according to OWID
351,Australia,AUS,2023,0.958,Oceania
1044,Canada,CAN,2023,0.939,North America
1158,Chile,CHL,2023,0.878,South America
2639,Hong Kong,HKG,2023,0.955,Asia
2707,Iceland,ISL,2023,0.972,Europe
5185,Seychelles,SYC,2023,0.848,Africa

In [13]:
min_hdi_per_region = df_filtered.groupby('World region according to OWID')['Human Development Index'].transform('min')

df_bottom = df_filtered[df_filtered['Human Development Index'] == min_hdi_per_region]

df_bottom

,Entity,Code,Year,Human Development Index,World region according to OWID
2503,Haiti,HTI,2023,0.554,North America
4624,Papua New Guinea,PNG,2023,0.576,Oceania
5498,South Sudan,SSD,2023,0.388,Africa
6128,Ukraine,UKR,2023,0.779,Europe
6365,Venezuela,VEN,2023,0.709,South America
6501,Yemen,YEM,2023,0.470,Asia

33      0.756630
91      0.899093
125     0.579611
149     0.899093
174     0.579611
          ...
6365    0.787167
6433    0.756630
6501    0.756630
6535    0.579611
6569    0.579611
Name: Human Development Index, Length: 192, dtype: float64